### ISSUE TITLE
Invalid code generated with default export modules

### ISSUE THREAD

**Issue by rdmurphy** [lukeed/bundt#6]
Hello @lukeed! Locally I bumped [Scroller](https://github.com/rdmurphy/scroller) to `1.1.3` and I believe I've found a newly introduced bug. [I have a minimal reproduction in this gist](https://gist.github.com/rdmurphy/b3a647ee09095895be8efe28d46e860b). (The `build.js` file was output after I [commented out this line](https://github.com/lukeed/bundt/blob/master/index.js#L44) in my `bundt` copy in `node_modules`.)

It appears the rewrite logic is making default exports become invalid after being parsed. So something like this:

```js
export default function square(n) {
  return n * n;
}
```

Becomes this:

```js
module.exports =(n) {
  return n * n;
}
```

However! It doesn't actually get this far, because once that is passed to `terser` it silently returns `undefined`, resulting in an error in `writeFileSync`.

```txt
TypeError [ERR_INVALID_ARG_TYPE]: The "buffer" argument must be of type string or an instance of Buffer, TypedArray, DataView, or ArrayBuffer. Received undefined
    at zlibBufferSync (zlib.js:162:13)
    at syncBufferWrapper (zlib.js:764:14)
    at write (/private/tmp/bundt-demo/node_modules/bundt/index.js:46:18)
    at run (/private/tmp/bundt-demo/node_modules/bundt/index.js:151:19)
    at Object.<anonymous> (/private/tmp/bundt-demo/node_modules/bundt/index.js:186:2)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'ERR_INVALID_ARG_TYPE'
```

**Comment by rdmurphy** [comment]
See now that the error above is actually with the gzip call, but I was definitely seeing it fall over at the `writeFileSync` line too. 🤔 Maybe only gets hit with UMD builds?

**Comment by lukeed** [comment]
Hey, thanks! You're right – it blew up within the terser stage. I'll leave that part alone & just fix the bad transform :)

**Comment by rdmurphy** [comment]
Awesome, thank you!

Just to not add noise elsewhere @lukeed — looks like an extra `console.log` snuck in to the bug fix release:

https://github.com/lukeed/bundt/blob/af897bfccde8722c71d2c685d2d93b820bfbf508/index.js#L132

**Comment by lukeed** [comment]
Shoot 🤦  lol
